version: "3.7"

services:
  app:
    build: .
    command: npm run dev
    ports:
      - "3333:3333"
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json



